[package]
name = "remy-core"
version = "0.1.0"
edition = "2021"

[dependencies]
chumsky = "0.9.3"
inkwell = { version = "0.5.0", features = ["llvm18-0"] }
logos = "0.14.1"

[dev-dependencies]
pretty_assertions = "1.4.1"
